# Generated by Django 5.1.5 on 2025-02-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
