# Generated by Django 5.1.5 on 2025-02-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_user_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_images/'),
        ),
    ]
