# Generated by Django 5.1.5 on 2025-01-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('about', models.TextField(blank=True, default='')),
                ('available', models.BooleanField()),
                ('fees', models.PositiveIntegerField()),
                ('address', models.JSONField()),
                ('date', models.DateField()),
                ('slots_booked', models.JSONField()),
            ],
        ),
    ]
