# Generated by Django 5.1.5 on 2025-01-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='date',
            new_name='join_date',
        ),
    ]
