# Generated by Django 5.1.5 on 2025-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
