# Generated by Django 5.1.5 on 2025-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slots_booked',
            field=models.JSONField(default=None, null=True),
        ),
    ]
