# Generated by Django 5.1.5 on 2025-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_slots_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slots_booked',
            field=models.JSONField(),
        ),
    ]
