# Generated by Django 5.1.5 on 2025-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_available_alter_doctor_slots_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slots_booked',
            field=models.JSONField(null=True),
        ),
    ]
